name: Update

on:
  # schedule:
    # - cron: "0 0 * * *"
  workflow_dispatch:
  
defaults:
  run:
    shell: bash

jobs:
  update-release:
    runs-on: ubuntu-latest
    env:
      ORIG_AUTHOR: ${{ secrets.ORIG_AUTHOR }}
      ORIG_REPO_NAME: ${{ secrets.ORIG_REPO_NAME }}
      ORIG_REPO_YT_ID: ${{ secrets.ORIG_REPO_YT_ID }}
      ORIG_PATH_NAME: ${{ secrets.ORIG_PATH_NAME }}
      MOD_AUTHOR: ${{ github.repository_owner }}
      MOD_REPOSITORY: ${{ github.repository }}
    steps:
      - name: Check & Install Missing Packages
        run: |
          sudo apt-get update -y
          for pkg in curl zip unzip jq moreutils aria2; do
            dpkg -s "$pkg" &>/dev/null || sudo apt-get install -y "$pkg"
          done
          
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Run Script
        run: |
          chmod +x run.sh
          ./run.sh
      
      - name: Set Environment Variables
        run: |
          MOD_REPO_NAME=$(basename "${{ env.MOD_REPOSITORY }}")
          MOD_REPO_YT_ID="$(echo ${MOD_REPO_NAME,,} | cut -d'-' -f1)-yt"
          
          echo "MOD_REPO_YT_ID=${MOD_REPO_YT_ID}" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Verify ZIP Files
        run: |
          if find releases -type f -name "*.zip" -quit; then
            echo "No ZIP files found in the release folder."
            exit 1
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "${{ env.TAG_NAME }}"
          body: "Automatically generated release."
          draft: false
          prerelease: false
          files: releases/*.zip
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull
          git add "${{ env.MOD_REPO_YT_ID }}" "TAG"
          git commit -m "Auto-update ${{ env.MOD_AUTHOR }} YouTube Lite Module"
          git push origin main
